
[datalink]
# datalink host, defaults to localhost
host='localhost'
# datalink port, defaults to 16000
port=16000
# Match regular expression pattern on stream ids, ex '.*/JSON'
match='.*/JSON'

[jsonl]
# JSONL Write pattern, usage similar to MSeedWrite in ringserver
# %n - network
# %s - station
# %l - location
# %c - channel
# %Y - year
# %j - day of year
# %H - hour
write='jsonl/%n/%s/%Y/%j/%n.%s.%l.%c.%Y.%j.%H.jsonl'
